In [2]:
# importing all the requuired packages

import pandas as pd
import numpy as np

In [5]:
# grabbing the dataset of kaggle
los_data = pd.read_csv("./Data/kaggle_los.csv")
los_data.head()

C:\Users\Deepjyoti\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Health Service Area,Hospital County,Operating Certificate Number,Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,Payment Typology 2,Payment Typology 3,Attending Provider License Number,Operating Provider License Number,Other Provider License Number,Birth Weight,Abortion Edit Indicator,Emergency Department Indicator,Total Charges,Total Costs
0,Western NY,Cattaraugus,401001.0,66.0,Olean General Hospital,50 to 69,147,F,White,Not Span/Hispanic,...,NaN,NaN,267162.0,NaN,NaN,0,N,Y,$5620.00,$4561.28
1,Western NY,Cattaraugus,401001.0,66.0,Olean General Hospital,18 to 29,147,F,White,Not Span/Hispanic,...,NaN,NaN,275408.0,NaN,NaN,0,N,Y,$7404.18,$6933.94
2,Western NY,Cattaraugus,401001.0,66.0,Olean General Hospital,30 to 49,147,M,White,Not Span/Hispanic,...,NaN,NaN,267162.0,NaN,NaN,0,N,Y,$7931.28,$7154.85
3,Western NY,Cattaraugus,401001.0,66.0,Olean General Hospital,50 to 69,147,F,White,Not Span/Hispanic,...,NaN,NaN,271326.0,NaN,NaN,0,N,Y,$11304.44,$4584.11
4,Western NY,Chautauqua,602001.0,103.0,Woman's Christian Association,50 to 69,147,M,White,Not Span/Hispanic,...,NaN,NaN,243034.0,NaN,NaN,0,N,Y,$8330.50,$4361.74

# Cleaning the data

In [7]:
# cgetting a sample data

los_data.sample(5)

,Health Service Area,Hospital County,Operating Certificate Number,Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,Payment Typology 2,Payment Typology 3,Attending Provider License Number,Operating Provider License Number,Other Provider License Number,Birth Weight,Abortion Edit Indicator,Emergency Department Indicator,Total Charges,Total Costs
765748,Hudson Valley,Rockland,4329000.0,779.0,Good Samaritan Hospital of Suffern,0 to 17,109,M,White,Not Span/Hispanic,...,NaN,NaN,221817.0,NaN,NaN,3200,N,N,$3069.83,$1152.50
1487009,New York City,Manhattan,7002017.0,1450.0,Lenox Hill Hospital,70 or Older,100,M,White,Not Span/Hispanic,...,Medicare,Medicaid,280072.0,NaN,NaN,0,N,Y,$52682.35,$11346.52
571017,Capital/Adiron,Clinton,901001.0,135.0,The University of Vermont Health Network - Cha...,30 to 49,129,M,White,Not Span/Hispanic,...,NaN,NaN,235668.0,NaN,NaN,0,N,Y,$10299.00,$4876.72
1563204,New York City,Manhattan,7002024.0,1456.0,Mount Sinai Hospital,30 to 49,104,M,Black/African American,Not Span/Hispanic,...,Medicaid,Self-Pay,267224.0,90270033.0,NaN,0,N,Y,$13038.03,$4014.78
301112,Finger Lakes,Schuyler,4823700.0,858.0,Schuyler Hospital,70 or Older,148,M,White,Unknown,...,NaN,NaN,260591.0,NaN,NaN,0,N,N,$5003.79,$3862.15

In [8]:
# checking for missing values

missing_values_count = los_data.isnull().sum()
missing_values_count

Health Service Area                       2911
Hospital County                           2911
Operating Certificate Number              2911
Facility Id                               2911
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                       4427
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCS Diagnosis Code                           0
CCS Diagnosis Description                    0
CCS Procedure Code                           0
CCS Procedure Description                    0
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description        112
APR Risk of Mortality                      112
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                      762346
Payment Typology 3                     1645570
Attending Provider License Number         2911
Operating Provider License Number       612848
Other Provider License Number          2275424
Birth Weight                                 0
Abortion Edit Indicator                      0
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
dtype: int64

In [9]:
# how many total missing values do we have?
total_cells = np.product(los_data.shape)
total_missing = missing_values_count.sum()

# percent of data that is missing
(total_missing/total_cells) * 100

6.121601582492342

In [10]:
# 6% data is empty

In [11]:
# look at the # of missing points in the first ten columns
missing_values_count[0:10]

Health Service Area             2911
Hospital County                 2911
Operating Certificate Number    2911
Facility Id                     2911
Facility Name                      0
Age Group                          0
Zip Code - 3 digits             4427
Gender                             0
Race                               0
Ethnicity                          0
dtype: int64

In [13]:
# remove all columns with at least one missing value
columns_with_na_dropped = los_data.dropna(axis=1)
columns_with_na_dropped.head()

,Facility Name,Age Group,Gender,Race,Ethnicity,Length of Stay,Type of Admission,Patient Disposition,Discharge Year,CCS Diagnosis Code,...,APR MDC Code,APR MDC Description,APR Severity of Illness Code,APR Medical Surgical Description,Payment Typology 1,Birth Weight,Abortion Edit Indicator,Emergency Department Indicator,Total Charges,Total Costs
0,Olean General Hospital,50 to 69,F,White,Not Span/Hispanic,5,Emergency,Home or Self Care,2015,657,...,19,Mental Diseases and Disorders,1,Medical,Medicaid,0,N,Y,$5620.00,$4561.28
1,Olean General Hospital,18 to 29,F,White,Not Span/Hispanic,8,Emergency,Home or Self Care,2015,657,...,19,Mental Diseases and Disorders,2,Medical,Medicaid,0,N,Y,$7404.18,$6933.94
2,Olean General Hospital,30 to 49,M,White,Not Span/Hispanic,8,Emergency,Home or Self Care,2015,657,...,19,Mental Diseases and Disorders,1,Medical,Medicaid,0,N,Y,$7931.28,$7154.85
3,Olean General Hospital,50 to 69,F,White,Not Span/Hispanic,4,Emergency,Home or Self Care,2015,128,...,4,Diseases and Disorders of the Respiratory System,1,Medical,Medicare,0,N,Y,$11304.44,$4584.11
4,Woman's Christian Association,50 to 69,M,White,Not Span/Hispanic,3,Emergency,Home or Self Care,2015,83,...,1,Diseases and Disorders of the Nervous System,2,Medical,Medicaid,0,N,Y,$8330.50,$4361.74

In [16]:
# checking for missing values

missing_values_count = columns_with_na_dropped.isnull().sum()
missing_values_count

Facility Name                       0
Age Group                           0
Gender                              0
Race                                0
Ethnicity                           0
Length of Stay                      0
Type of Admission                   0
Patient Disposition                 0
Discharge Year                      0
CCS Diagnosis Code                  0
CCS Diagnosis Description           0
CCS Procedure Code                  0
CCS Procedure Description           0
APR DRG Code                        0
APR DRG Description                 0
APR MDC Code                        0
APR MDC Description                 0
APR Severity of Illness Code        0
APR Medical Surgical Description    0
Payment Typology 1                  0
Birth Weight                        0
Abortion Edit Indicator             0
Emergency Department Indicator      0
Total Charges                       0
Total Costs                         0
dtype: int64

In [17]:
# how many total missing values do we have?
total_cells = np.product(columns_with_na_dropped.shape)
total_missing = missing_values_count.sum()

# percent of data that is missing
(total_missing/total_cells) * 100

0.0